export interface BuildingType {
  slug: string;
  name: string;
  category: string;
  description: string;
  complexity: number;
  basePatentVolume: number;
  filingChallenge: string;
  faqQuestion: string;
  faqAnswer: string;
}

export const buildingTypes: BuildingType[] = [
  {
    slug: "single-family-residential",
    name: "Single-Family Residential",
    category: "Residential",
    description: "Standard detached residential home structures, focusing on framing, insulation systems, and plumbing integrations.",
    complexity: 2,
    basePatentVolume: 1200,
    filingChallenge: "Finding novelty in standard wood-framing or traditional foundation methods can be difficult due to heavy prior art.",
    faqQuestion: "Can I patent a custom layout of a residential home?",
    faqAnswer: "Generally, floor plans themselves are protected by copyright, not patents. To qualify for a patent, the structure must incorporate a novel, non-obvious engineering method or mechanical system."
  },
  {
    slug: "multi-family-residential",
    name: "Multi-Family Residential",
    category: "Residential",
    description: "Multi-family residential buildings, duplexes, and townhomes with modular wall assemblies.",
    complexity: 3,
    basePatentVolume: 1800,
    filingChallenge: "Balancing fire-rating compliance with modular acoustic barriers creates proprietary engineering challenges.",
    faqQuestion: "How do acoustic ratings affect multi-family building patents?",
    faqAnswer: "Acoustic insulation assemblies that achieve higher sound transmission class (STC) ratings through novel material combinations can be patented as utility innovations."
  },
  {
    slug: "low-rise-apartment",
    name: "Low-Rise Apartment",
    category: "Residential",
    description: "Low-rise multi-story apartments utilizing light-gauge steel or mass timber structures.",
    complexity: 3,
    basePatentVolume: 2100,
    filingChallenge: "Establishing structural stability and wind-load distribution using modular multi-family frames.",
    faqQuestion: "Are modular apartment joints patentable?",
    faqAnswer: "Yes. Connecting brackets and interlocking joint mechanisms designed for fast assembly of low-rise components are highly patentable."
  },
  {
    slug: "high-rise-condominium",
    name: "High-Rise Condominium",
    category: "Residential",
    description: "Multi-story luxury residential condominiums with high-performance curtain walls.",
    complexity: 4,
    basePatentVolume: 3400,
    filingChallenge: "Mitigating seismic shear forces and elevator shaft pressure differentials at extreme heights.",
    faqQuestion: "What is the primary patent risk for high-rise condos?",
    faqAnswer: "Seismic damping systems and high-pressure plumbing stacks have vast amounts of existing patent history, requiring careful novelty analysis."
  },
  {
    slug: "modular-home",
    name: "Modular Home",
    category: "Residential",
    description: "Prefabricated residential housing modules built off-site and transported for final assembly.",
    complexity: 3,
    basePatentVolume: 4200,
    filingChallenge: "Designing load-bearing lifting points and transportable foundation brackets.",
    faqQuestion: "Can prefab assembly lines be patented?",
    faqAnswer: "Yes, both the physical modular joints and the manufacturing assembly line processes can be patented separately."
  },
  {
    slug: "commercial-office-building",
    name: "Commercial Office Building",
    category: "Commercial",
    description: "Professional office structures focusing on open-span layouts and integrated smart HVAC systems.",
    complexity: 3,
    basePatentVolume: 2500,
    filingChallenge: "Integrating smart air handling controls with traditional structural concrete cores.",
    faqQuestion: "Can energy-saving office HVAC designs be patented?",
    faqAnswer: "Yes. Advanced thermodynamic cycling loops and digital sensor controllers qualify for utility patents if they produce non-obvious efficiency gains."
  },
  {
    slug: "corporate-headquarters",
    name: "Corporate Headquarters",
    category: "Commercial",
    description: "Large scale custom enterprise headquarters incorporating architectural landmarks and advanced building management systems.",
    complexity: 4,
    basePatentVolume: 3100,
    filingChallenge: "Securing architectural patents for unique facade structures alongside building utility patents.",
    faqQuestion: "What is the difference between utility and design patents for corporate offices?",
    faqAnswer: "Design patents protect the visual aesthetic and shape of the facade, while utility patents protect the mechanical systems or load-distribution frameworks."
  },
  {
    slug: "medical-office",
    name: "Medical Office",
    category: "Commercial",
    description: "Outpatient medical clinics requiring strict radiation shielding, sanitization materials, and gas routing.",
    complexity: 4,
    basePatentVolume: 3500,
    filingChallenge: "Ensuring gas line safety mechanisms comply with healthcare building code standards while keeping filing novelty.",
    faqQuestion: "Are lead-shielding wall panels patentable?",
    faqAnswer: "Yes. Lightweight, composite shielding drywall that replaces heavy lead sheeting is a prime candidate for materials engineering patents."
  },
  {
    slug: "dental-clinic",
    name: "Dental Clinic",
    category: "Commercial",
    description: "Dental facilities specialized in negative-pressure treatment rooms and particulate vacuum networks.",
    complexity: 3,
    basePatentVolume: 1900,
    filingChallenge: "Designing silent, high-power vacuum manifolds that fit within standard floor joists.",
    faqQuestion: "Can dental suction configurations be patented?",
    faqAnswer: "Only if the mechanical manifold design represents a new, non-obvious air-flow solution that increases static pressure."
  },
  {
    slug: "retail-shopping-mall",
    name: "Retail Shopping Mall",
    category: "Commercial",
    description: "Sprawling commercial shopping centers with large span glass skylights and centralized thermal loops.",
    complexity: 4,
    basePatentVolume: 2800,
    filingChallenge: "Handling major thermal expansion in steel-framed skylights across 500+ meters.",
    faqQuestion: "How do expansion joints impact retail patents?",
    faqAnswer: "High-movement expansion seals that prevent water ingress while accommodating structural shifting are actively patented."
  },
  {
    slug: "strip-mall",
    name: "Strip Mall",
    category: "Commercial",
    description: "Single-story linear retail spaces featuring concrete tilt-up walls and quick-install roofing structures.",
    complexity: 2,
    basePatentVolume: 900,
    filingChallenge: "Overcoming standard structural patterns; low complexity limits patent opportunities.",
    faqQuestion: "Is there IP potential in strip mall construction?",
    faqAnswer: "Yes, specifically in modular concrete casting templates and quick-locking roof panels that speed up construction schedules."
  },
  {
    slug: "supermarket",
    name: "Supermarket",
    category: "Commercial",
    description: "Large retail food centers requiring complex refrigeration loops, ambient humidity control, and high-load display slabs.",
    complexity: 3,
    basePatentVolume: 2300,
    filingChallenge: "Integrating condensation runoff drainage systems with under-slab cooling networks.",
    faqQuestion: "Can commercial cold-aisle designs be patented?",
    faqAnswer: "Yes. Fluid dynamic designs that contain cold air within supermarket display aisles using air-curtain dynamics are patentable."
  },
  {
    slug: "department-store",
    name: "Department Store",
    category: "Commercial",
    description: "Large multi-floor retail buildings with centralized escalator columns and fire containment zones.",
    complexity: 3,
    basePatentVolume: 1500,
    filingChallenge: "Drafting curtain wall fire barrier systems that deploy automatically without blocking escape routes.",
    faqQuestion: "Are automated fire-curtain mechanisms patentable?",
    faqAnswer: "Yes. Mechanical deployment triggers that activate under thermal expansion without electrical power are highly patentable."
  },
  {
    slug: "boutique-shop",
    name: "Boutique Shop",
    category: "Commercial",
    description: "Small footprint bespoke retail stores focusing on premium acoustic design and integrated luxury lighting.",
    complexity: 2,
    basePatentVolume: 800,
    filingChallenge: "Proving industrial utility for custom visual and acoustic boutique installations.",
    faqQuestion: "Can aesthetic lighting tracks be patented?",
    faqAnswer: "Yes. If the lighting track incorporates a new magnetic electrical bus structure, it qualifies for a utility patent."
  },
  {
    slug: "warehouse-distribution-center",
    name: "Warehouse Distribution Center",
    category: "Industrial",
    description: "High-volume logistics warehouses with high-flatness concrete slabs and heavy rack loads.",
    complexity: 3,
    basePatentVolume: 5800,
    filingChallenge: "Achieving F-number concrete flatness ratings through automated laser-screed pouring machines.",
    faqQuestion: "Are concrete pouring leveling methods patentable?",
    faqAnswer: "Yes, automated leveling control systems and concrete curing compounds that prevent shrinkage curl are patentable."
  },
  {
    slug: "cold-storage-facility",
    name: "Cold Storage Facility",
    category: "Industrial",
    description: "Sub-zero industrial food and pharma storage requiring deep floor slab insulation and thermal break pillars.",
    complexity: 4,
    basePatentVolume: 4900,
    filingChallenge: "Preventing frost heave beneath insulated concrete slabs in continuous freezing conditions.",
    faqQuestion: "How do you patent a frost-heave prevention system?",
    faqAnswer: "You patent the mechanical sub-slab air ventilation structure or the electronic temperature control loop that pumps warm glycol through sub-floor grids."
  },
  {
    slug: "data-center",
    name: "Data Center",
    category: "Industrial",
    description: "Hyperscale computing infrastructure requiring liquid-to-chip cooling, high-density power distribution, and seismic isolation.",
    complexity: 5,
    basePatentVolume: 12000,
    filingChallenge: "Filing patents for hot/cold aisle containment systems and modular battery rack cooling loops.",
    faqQuestion: "What patents are most common in data centers?",
    faqAnswer: "Liquid cooling manifolds, hot-swap battery cooling containment systems, and high-frequency power busbars represent the highest volume of filings."
  },
  {
    slug: "server-farm",
    name: "Server Farm",
    category: "Industrial",
    description: "Regional processing server buildings utilizing external air-economizers and modular server pods.",
    complexity: 4,
    basePatentVolume: 8700,
    filingChallenge: "Filing air-economizer moisture filtration systems that run under extreme CFM volume.",
    faqQuestion: "Are modular server pod housings patentable?",
    faqAnswer: "Yes. Interlocking server housings with integrated coolant quick-connect valves are highly sought-after utility patents."
  },
  {
    slug: "light-industrial-factory",
    name: "Light Industrial Factory",
    category: "Industrial",
    description: "Small assembly facilities requiring flexible crane runways and modular production line hookups.",
    complexity: 3,
    basePatentVolume: 3100,
    filingChallenge: "Filing patents for modular utility drops that supply compressed air, water, and power simultaneously.",
    faqQuestion: "Can factory runway crane mounts be patented?",
    faqAnswer: "Yes. Crane rail connections that damp mechanical vibration to protect building columns are patentable."
  },
  {
    slug: "heavy-manufacturing-plant",
    name: "Heavy Manufacturing Plant",
    category: "Industrial",
    description: "Massive industrial processing plants with heavy machinery foundations and high thermal emission ventilation.",
    complexity: 5,
    basePatentVolume: 9200,
    filingChallenge: "Designing isolated concrete foundations that support 500-ton stamping presses without cracking.",
    faqQuestion: "How do you patent a heavy machine foundation?",
    faqAnswer: "By patenting the layered shock-absorption system, composed of synthetic polymers and post-tensioned steel anchors."
  },
  {
    slug: "chemical-processing-refinery",
    name: "Chemical Processing Refinery",
    category: "Industrial",
    description: "Refineries requiring explosion-proof electrical systems and corrosion-resistant piping frameworks.",
    complexity: 5,
    basePatentVolume: 15400,
    filingChallenge: "Patenting anti-corrosive alloy joins that withstand high-pressure acidic chemical transfers.",
    faqQuestion: "What class of patents are chemical refineries eligible for?",
    faqAnswer: "Materials engineering patents, process patents for chemical routing, and utility patents for explosive gas detection systems."
  },
  {
    slug: "automotive-assembly-plant",
    name: "Automotive Assembly Plant",
    category: "Industrial",
    description: "High-speed robotic automotive manufacturing facilities with overhead conveyor tracks.",
    complexity: 5,
    basePatentVolume: 11000,
    filingChallenge: "Securing patents for high-speed overhead carrier clamps that coordinate with automated robotic arms.",
    faqQuestion: "Are factory conveyor routing algorithms patentable?",
    faqAnswer: "Yes, software algorithms that run assembly plant logistics and avoid collisions in real-time are patentable as process utilities."
  },
  {
    slug: "aerospace-hangar",
    name: "Aerospace Hangar",
    category: "Industrial",
    description: "Wide-span aircraft hangars featuring massive sliding doors and high-capacity fire foam deluge systems.",
    complexity: 4,
    basePatentVolume: 6100,
    filingChallenge: "Supporting structural roof trusses that spans 150+ meters without intermediate pillars.",
    faqQuestion: "Can hangar door seals be patented?",
    faqAnswer: "Yes. Custom pressure-tight seals that resist jet blast forces and prevent thermal loss are patentable."
  },
  {
    slug: "pharmaceutical-laboratory",
    name: "Pharmaceutical Laboratory",
    category: "Industrial",
    description: "Cleanroom pharmaceutical research labs requiring biosafety level 4 containment systems.",
    complexity: 5,
    basePatentVolume: 13500,
    filingChallenge: "Ensuring zero-leak airlock doors maintain pressure seal integrity during power failure.",
    faqQuestion: "Are lab airlock pressure seals patentable?",
    faqAnswer: "Yes. Magnetic passive airlock seals that hold pressure without electrical power are highly patentable."
  },
  {
    slug: "research-and-development-facility",
    name: "Research and Development Facility",
    category: "Industrial",
    description: "Bespoke technology testing facilities with integrated electromagnetic interference (EMI) shielding.",
    complexity: 4,
    basePatentVolume: 7400,
    filingChallenge: "Designing shielding walls that absorb microwave frequencies up to 100 GHz.",
    faqQuestion: "What is the patent potential for EMI shielding?",
    faqAnswer: "Composite shielding materials and honeycomb vent structures that allow airflow while blocking RF signals are prime IP targets."
  },
  {
    slug: "primary-school",
    name: "Primary School",
    category: "Educational",
    description: "Early childhood education buildings incorporating child-safe materials and passive solar heating.",
    complexity: 2,
    basePatentVolume: 1100,
    filingChallenge: "Finding patentable novelty in standard child safety door hinges or non-toxic wall coatings.",
    faqQuestion: "Can child-safe school door hinges be patented?",
    faqAnswer: "Yes. Hinges designed to completely eliminate finger pinch-points through rolling guards are patentable."
  },
  {
    slug: "middle-school",
    name: "Middle School",
    category: "Educational",
    description: "Educational facilities with high-traffic corridors and modular acoustic classroom partitions.",
    complexity: 3,
    basePatentVolume: 1400,
    filingChallenge: "Ensuring modular acoustic walls meet code fire-ratings while achieving sound dampening.",
    faqQuestion: "Are classroom divider wall tracks patentable?",
    faqAnswer: "Yes. Rail tracks that automatically lock into place under seismic shaking can be patented."
  },
  {
    slug: "high-school",
    name: "High School",
    category: "Educational",
    description: "Comprehensive secondary schools incorporating athletic facilities and science lab wings.",
    complexity: 3,
    basePatentVolume: 1700,
    filingChallenge: "Integrating lab gas safety valve networks with centralized school fire alarms.",
    faqQuestion: "What IP is generated during high school construction?",
    faqAnswer: "Mainly mechanical innovations in student locker lock mechanics and automated laboratory gas shut-off systems."
  },
  {
    slug: "university-campus",
    name: "University Campus",
    category: "Educational",
    description: "Sprawling educational facilities with centralized district heating and research infrastructure.",
    complexity: 4,
    basePatentVolume: 4300,
    filingChallenge: "Designing energy monitoring software loops that cross-reference 100+ separate campus buildings.",
    faqQuestion: "Can university district heating loops be patented?",
    faqAnswer: "Yes. Co-generation control loops that share heat between high-demand computing facilities and dorms are patentable."
  },
  {
    slug: "college-lecture-hall",
    name: "College Lecture Hall",
    category: "Educational",
    description: "High-capacity tiered seating lecture auditoriums with specialized acoustics and projection layouts.",
    complexity: 3,
    basePatentVolume: 2100,
    filingChallenge: "Formulating curved acoustic wall panel designs that direct sound without creating echoes.",
    faqQuestion: "Are theater-style seating mechanisms patentable?",
    faqAnswer: "Yes. Seat hinges that auto-retract silently using fluid dampers are actively patented."
  },
  {
    slug: "student-dormitory",
    name: "Student Dormitory",
    category: "Educational",
    description: "Dense multi-family housing utilizing modular modular bathroom pods and high-durability systems.",
    complexity: 3,
    basePatentVolume: 1900,
    filingChallenge: "Creating fast-install bathroom pods that plug directly into main building drainage columns.",
    faqQuestion: "Are prefabricated bathroom pods patentable?",
    faqAnswer: "Yes. The frame structure and the quick-connect plumbing adapters are major patent targets."
  },
  {
    slug: "vocational-training-center",
    name: "Vocational Training Center",
    category: "Educational",
    description: "Practical engineering education centers with integrated dust collection and welding exhaust hoods.",
    complexity: 3,
    basePatentVolume: 1600,
    filingChallenge: "Patenting energy-saving dust collector fans that modulate speed based on active machine usage.",
    faqQuestion: "Can industrial dust collectors qualify for patents?",
    faqAnswer: "Yes, specifically air-cyclone separators and filter-cleaning solenoid pulse systems."
  },
  {
    slug: "public-library",
    name: "Public Library",
    category: "Educational",
    description: "Civic book archival repositories requiring precise humidity control and fire suppression.",
    complexity: 3,
    basePatentVolume: 2200,
    filingChallenge: "Designing fire suppression systems that extinguish fire without damaging books (waterless systems).",
    faqQuestion: "What is waterless fire suppression IP?",
    faqAnswer: "It involves gas deluge systems (like Inergen or Novec) that lower oxygen levels to extinguish fire while preserving paper archives."
  },
  {
    slug: "community-center",
    name: "Community Center",
    category: "Educational",
    description: "Multi-purpose public assembly buildings with open gymnasium spaces and modular event rooms.",
    complexity: 2,
    basePatentVolume: 1000,
    filingChallenge: "Designing folding divider walls that lock flush to the floor without floor tracks.",
    faqQuestion: "Are floor-trackless folding dividers patentable?",
    faqAnswer: "Yes, clamping mechanisms that drop sound-seals from the door bottom onto the floor are patentable."
  },
  {
    slug: "museum",
    name: "Museum",
    category: "Educational",
    description: "High-security artifact display buildings with seismic display cases and lighting grids.",
    complexity: 4,
    basePatentVolume: 3900,
    filingChallenge: "Securing patents for high-security dynamic glass display cases that resist physical impact and UV radiation.",
    faqQuestion: "Can museum display security cases be patented?",
    faqAnswer: "Yes. Dynamic gas-purged display cases that monitor pressure differentials to detect tampering are patentable."
  },
  {
    slug: "art-gallery",
    name: "Art Gallery",
    category: "Educational",
    description: "Premium display spaces with customized lighting control networks and micro-climate art storage.",
    complexity: 3,
    basePatentVolume: 1800,
    filingChallenge: "Filing patents for gallery lighting rails that distribute low-voltage power and digital control signals.",
    faqQuestion: "Can lighting rail control channels be patented?",
    faqAnswer: "Yes, the digital bus communication protocol integrated within the lighting track is patentable."
  },
  {
    slug: "science-center",
    name: "Science Center",
    category: "Educational",
    description: "Interactive science educational facilities featuring dome planetariums and high-voltage display chambers.",
    complexity: 4,
    basePatentVolume: 4700,
    filingChallenge: "Designing Faraday cage structures that isolate 1-million-volt Tesla coil discharges from building electronics.",
    faqQuestion: "How do Faraday shields apply for patents?",
    faqAnswer: "Grounding connection brackets and mesh panels that maintain shield integrity across building seams are patentable."
  },
  {
    slug: "general-hospital",
    name: "General Hospital",
    category: "Healthcare",
    description: "Critical care medical centers featuring automated oxygen networks, back-up power stations, and patient quarantine zones.",
    complexity: 5,
    basePatentVolume: 18500,
    filingChallenge: "Filing emergency hospital backup power switches that transfer load under 5 milliseconds.",
    faqQuestion: "What makes hospital power grids patentable?",
    faqAnswer: "Fast-acting solid-state transfer switches and automated load-shedding control software are highly patentable."
  },
  {
    slug: "specialized-surgery-clinic",
    name: "Specialized Surgery Clinic",
    category: "Healthcare",
    description: "Surgical facilities built around laminar air-flow surgical booths and high-stability equipment mounts.",
    complexity: 5,
    basePatentVolume: 14200,
    filingChallenge: "Ensuring laminar flow ceiling vents maintain sterile air currents over the patient area.",
    faqQuestion: "Can surgical laminar flow configurations be patented?",
    faqAnswer: "Yes. Vents with dual-velocity nozzles that prevent ambient room air from entering the sterile surgical zone are actively patented."
  },
  {
    slug: "urgent-care-center",
    name: "Urgent Care Center",
    category: "Healthcare",
    description: "Rapid triage medical clinics focusing on quick access floor layouts and automated patient check-in kiosks.",
    complexity: 3,
    basePatentVolume: 3200,
    filingChallenge: "Designing negative-pressure waiting room air loops that filter airborne pathogens before recycling.",
    faqQuestion: "Are air sanitizing duct inserts patentable?",
    faqAnswer: "Yes. UV-C sanitizing duct modules with reflective internal chambers are prime candidates for utility patents."
  },
  {
    slug: "nursing-home",
    name: "Nursing Home",
    category: "Healthcare",
    description: "Senior housing facilities featuring continuous health tracking sensors and fall-dampening floor underlays.",
    complexity: 3,
    basePatentVolume: 2900,
    filingChallenge: "Formulating shock-absorbing floor materials that prevent hip fractures without feeling soft underfoot.",
    faqQuestion: "Can fall-dampening flooring be patented?",
    faqAnswer: "Yes. Interlocking foam-subfloor tiles that stiffen under high impact but cushion under walking loads are patentable."
  },
  {
    slug: "assisted-living-facility",
    name: "Assisted Living Facility",
    category: "Healthcare",
    description: "Semi-independent senior living homes with automated lighting profiles and emergency grab-rail triggers.",
    complexity: 3,
    basePatentVolume: 2700,
    filingChallenge: "Patenting pressure-sensor floor baseboards that detect patient falls and notify staff.",
    faqQuestion: "Are emergency baseboard sensors patentable?",
    faqAnswer: "Yes. Baseboard arrays with capacitive proximity sensors are actively patentable in healthcare IoT."
  },
  {
    slug: "rehabilitation-center",
    name: "Rehabilitation Center",
    category: "Healthcare",
    description: "Physical therapy clinics utilizing hydrotherapy pools and gait analysis walking tracks.",
    complexity: 4,
    basePatentVolume: 4100,
    filingChallenge: "Designing underwater pool treadmills that run continuously in highly chlorinated saline water.",
    faqQuestion: "Can hydrotherapy treadmill drives be patented?",
    faqAnswer: "Yes. Magnetic-drive seals that prevent saline water from reaching the electric motor are highly patentable."
  },
  {
    slug: "veterinary-hospital",
    name: "Veterinary Hospital",
    category: "Healthcare",
    description: "Animal care facilities featuring specialized acoustic isolation panels and animal-safe washdowns.",
    complexity: 3,
    basePatentVolume: 2200,
    filingChallenge: "Developing sound-absorbing dog kennel walls that resist animal urine and power-washing chemical cleaners.",
    faqQuestion: "Are kennel sound panels patentable?",
    faqAnswer: "Yes. Closed-cell polymer panels that absorb sound without retaining moisture are patentable."
  },
  {
    slug: "luxury-hotel",
    name: "Luxury Hotel",
    category: "Hospitality",
    description: "Premium high-density hospitality lodging featuring automated room comfort controls and structural soundproof walls.",
    complexity: 4,
    basePatentVolume: 4800,
    filingChallenge: "Integrating automated HVAC valves that detect window opening and shut down room systems instantly.",
    faqQuestion: "Can hotel room power savers be patented?",
    faqAnswer: "Yes. Smart card slot switches and bed-occupancy sensor loops that cut power to non-essential outlets are patentable."
  },
  {
    slug: "budget-motel",
    name: "Budget Motel",
    category: "Hospitality",
    description: "Low-rise hospitality complexes built with pre-assembled modular guestrooms and simple structural frames.",
    complexity: 2,
    basePatentVolume: 1200,
    filingChallenge: "Patent options are limited due to standard wood/concrete structure formats.",
    faqQuestion: "Can modular motel room linkages be patented?",
    faqAnswer: "Yes, mechanical joints that share wall cavities for plumbing but maintain acoustic isolation are patentable."
  },
  {
    slug: "boutique-resort",
    name: "Boutique Resort",
    category: "Hospitality",
    description: "Eco-resort structures featuring sustainable building materials and greywater treatment loops.",
    complexity: 3,
    basePatentVolume: 2400,
    filingChallenge: "Designing low-power composting sanitation systems that process high volume without odor.",
    faqQuestion: "Can resort greywater loops be patented?",
    faqAnswer: "Yes. Multi-stage bio-filtration panels using local soil and root micro-flora are patentable."
  },
  {
    slug: "extended-stay-suite",
    name: "Extended Stay Suite",
    category: "Hospitality",
    description: "Kitchenette-equipped suites requiring compact fire containment and modular storage systems.",
    complexity: 3,
    basePatentVolume: 1900,
    filingChallenge: "Drafting patents for fold-down kitchenettes with automated electrical disconnect switches.",
    faqQuestion: "Are folding kitchenette safety switches patentable?",
    faqAnswer: "Yes. Switches that disconnect power to the stove when the unit is folded away are patentable."
  },
  {
    slug: "bed-and-breakfast",
    name: "Bed and Breakfast",
    category: "Hospitality",
    description: "Historic or themed small lodging structures focusing on fire-safety retrofitting.",
    complexity: 2,
    basePatentVolume: 700,
    filingChallenge: "Retrofitting modern sprinkler lines within historic lath-and-plaster structures without damage.",
    faqQuestion: "Can historic retrofit sprinkler nozzles be patented?",
    faqAnswer: "Yes. Ultra-low-profile sprinkler heads that insert through plaster walls without large holes are patentable."
  },
  {
    slug: "hostel",
    name: "Hostel",
    category: "Hospitality",
    description: "Shared lodging dormitories featuring modular bunk structures with integrated ventilation.",
    complexity: 2,
    basePatentVolume: 900,
    filingChallenge: "Designing bunk beds that route individual fresh air ducts to each cabin capsule.",
    faqQuestion: "Are hostel cabin ventilation modules patentable?",
    faqAnswer: "Yes. Compact fan silencer ducts that feed air to enclosed bunk compartments are patentable."
  },
  {
    slug: "fine-dining-restaurant",
    name: "Fine Dining Restaurant",
    category: "Hospitality",
    description: "Premium kitchens requiring automated grease hood cleaners and quiet dining room air systems.",
    complexity: 3,
    basePatentVolume: 2900,
    filingChallenge: "Designing grease hoods that spray cleaning surfactant automatically after high-temperature cooking events.",
    faqQuestion: "Are self-cleaning grease hoods patentable?",
    faqAnswer: "Yes. Manifolds that inject surfactant into hood exhaust lines based on grease-sensor readings are patentable."
  },
  {
    slug: "fast-food-outlet",
    name: "Fast Food Outlet",
    category: "Hospitality",
    description: "High-speed kitchen outlets featuring centralized frying oil filtration systems and automated soda dispensers.",
    complexity: 3,
    basePatentVolume: 3800,
    filingChallenge: "Patenting automated fry oil filtration piping that works under high temperatures without pump clogging.",
    faqQuestion: "Can fast food fryer oil systems be patented?",
    faqAnswer: "Yes, vacuum filtration cycles and automated oil quality sensor probes are patentable."
  },
  {
    slug: "cafeteria",
    name: "Cafeteria",
    category: "Hospitality",
    description: "High-capacity public food halls featuring tray conveyor tracks and automated dish washing stations.",
    complexity: 3,
    basePatentVolume: 2100,
    filingChallenge: "Filing patents for dish scrap sorting conveyors that use optical camera sorters.",
    faqQuestion: "Can cafeteria tray sorters be patented?",
    faqAnswer: "Yes. Machine vision systems that classify silverware vs food scrap and sort them are patentable."
  },
  {
    slug: "coffee-shop",
    name: "Coffee Shop",
    category: "Hospitality",
    description: "Small beverage shops with specialized under-counter water filtration systems and steam exhaust loops.",
    complexity: 2,
    basePatentVolume: 1500,
    filingChallenge: "Designing water filtration systems that maintain mineral PPM for optimal espresso extraction.",
    faqQuestion: "Are water remineralization systems patentable?",
    faqAnswer: "Yes. Reverse-osmosis blending valves that dose minerals back into espresso water lines are patentable."
  },
  {
    slug: "bakery",
    name: "Bakery",
    category: "Hospitality",
    description: "Commercial baking operations utilizing high-thermal mass deck ovens and steam injection racks.",
    complexity: 3,
    basePatentVolume: 2300,
    filingChallenge: "Designing deck oven steam injectors that distribute steam evenly across 10-meter stone hearths.",
    faqQuestion: "Are steam-injection bread ovens patentable?",
    faqAnswer: "Yes, the steam nozzle manifold configuration and pressure venting logic are patentable."
  },
  {
    slug: "craft-brewery",
    name: "Craft Brewery",
    category: "Hospitality",
    description: "Bespoke brewing facilities featuring specialized fermentation tanks and wastewater pretreatment tanks.",
    complexity: 4,
    basePatentVolume: 3900,
    filingChallenge: "Patenting custom dimple-jacket glycol cooling loops on fermentation vessels.",
    faqQuestion: "Can brewery fermentation tank jackets be patented?",
    faqAnswer: "Yes. High-efficiency dimple jacket weld layouts that optimize glycol coolant turbulence are patentable."
  },
  {
    slug: "winery",
    name: "Winery",
    category: "Hospitality",
    description: "Wine production cellars requiring concrete aging tanks and dynamic humidity cave air systems.",
    complexity: 3,
    basePatentVolume: 2500,
    filingChallenge: "Designing double-walled concrete fermentation vats with integrated cooling pipes.",
    faqQuestion: "Are concrete wine tank forms patentable?",
    faqAnswer: "Yes. Concrete tanks with internal tubing arrays that control grape must temperature are patentable."
  },
  {
    slug: "sports-stadium",
    name: "Sports Stadium",
    category: "Specialized",
    description: "Mega-scale stadium structures with retractable roof trusses and high-density audience seating.",
    complexity: 5,
    basePatentVolume: 14500,
    filingChallenge: "Designing retractable roof guide rollers that support 2,000-ton steel spans during high winds.",
    faqQuestion: "Are stadium retractable roof drives patentable?",
    faqAnswer: "Yes. Cable-drive assemblies and hydraulic locking claws that secure the roof panels are patentable."
  },
  {
    slug: "indoor-arena",
    name: "Indoor Arena",
    category: "Specialized",
    description: "Multi-purpose arenas featuring retractable seating decks and quick-change ice floor systems.",
    complexity: 4,
    basePatentVolume: 8200,
    filingChallenge: "Filing patents for ice rink cooling pipes that freeze concrete slabs under 2 hours.",
    faqQuestion: "Are Arena ice floor concrete structures patentable?",
    faqAnswer: "Yes. Concrete slabs containing titanium-alloy coolant pipes that resist freeze-thaw cracking are patentable."
  },
  {
    slug: "gymnasium",
    name: "Gymnasium",
    category: "Specialized",
    description: "Athletic facilities with spring-loaded hardwood floors and high-volume ventilation systems.",
    complexity: 2,
    basePatentVolume: 1300,
    filingChallenge: "Designing spring clips that allow hardwood floors to flex without squeaking.",
    faqQuestion: "Are athletic floor clips patentable?",
    faqAnswer: "Yes. Interlocking rubber-cushioned metal clips that attach wood floors to sub-concrete are patentable."
  },
  {
    slug: "fitness-center",
    name: "Fitness Center",
    category: "Specialized",
    description: "Health clubs featuring cardio machine kinetic energy harvesting loops and heavy weight drops.",
    complexity: 3,
    basePatentVolume: 2600,
    filingChallenge: "Patenting grid-tie inverters that aggregate kinetic energy from 50+ elliptical machines.",
    faqQuestion: "Can cardio energy recovery systems be patented?",
    faqAnswer: "Yes. Micro-inverters integrated into exercise machines that feed power back to the building grid are patentable."
  },
  {
    slug: "swimming-pool-complex",
    name: "Swimming Pool Complex",
    category: "Specialized",
    description: "Aquatic centers featuring high-capacity sand filters, UV sanitation tubes, and humidity exhaust fans.",
    complexity: 3,
    basePatentVolume: 3400,
    filingChallenge: "Filing patents for pool gutter drainage slots that reduce wave rebound during swim races.",
    faqQuestion: "Are swim race wave-damping gutters patentable?",
    faqAnswer: "Yes. Gutter baffles that absorb wave energy to prevent splashback into lanes are patentable."
  },
  {
    slug: "theater",
    name: "Theater",
    category: "Specialized",
    description: "Performance stages featuring fly towers, motorized rigging, and orchestra lift platforms.",
    complexity: 4,
    basePatentVolume: 5800,
    filingChallenge: "Designing motorized stage winches that hold 5 tons and run silently at 2 meters per second.",
    faqQuestion: "Are stage winch brake systems patentable?",
    faqAnswer: "Yes. Dual-redundant electromagnetic brakes that engage silently in under 50 milliseconds are patentable."
  },
  {
    slug: "cinema-multiplex",
    name: "Cinema Multiplex",
    category: "Specialized",
    description: "Multi-theater cinemas requiring absolute room-to-room acoustic isolation (box-in-a-box).",
    complexity: 3,
    basePatentVolume: 3900,
    filingChallenge: "Designing neoprene acoustic isolators that decouple theater wall studs from building columns.",
    faqQuestion: "Can cinema isolation hangers be patented?",
    faqAnswer: "Yes. Hangers with specialized elastomer inserts that block low-frequency subwoofer vibrations are patentable."
  },
  {
    slug: "concert-hall",
    name: "Concert Hall",
    category: "Specialized",
    description: "Bespoke orchestral halls featuring variable acoustic banners and wood resonance chambers.",
    complexity: 4,
    basePatentVolume: 6700,
    filingChallenge: "Securing patents for automated acoustic wall panels that change angle to match orchestra size.",
    faqQuestion: "Are variable acoustic panels patentable?",
    faqAnswer: "Yes. Hinged wall panels that adjust position using silent electric screw actuators are patentable."
  },
  {
    slug: "convention-center",
    name: "Convention Center",
    category: "Specialized",
    description: "Mega-scale exhibition halls requiring utility floor trenches and long-span steel roofs.",
    complexity: 4,
    basePatentVolume: 7400,
    filingChallenge: "Designing floor trenches that house high-voltage, water, data, and drainage connections in one box.",
    faqQuestion: "Are convention floor utility trenches patentable?",
    faqAnswer: "Yes. Water-tight floor hatches that support forklift traffic while protecting cables are patentable."
  },
  {
    slug: "exhibition-hall",
    name: "Exhibition Hall",
    category: "Specialized",
    description: "Large open spaces featuring high-capacity overhead rigging beams and automated crowd doors.",
    complexity: 3,
    basePatentVolume: 4900,
    filingChallenge: "Designing overhead truss clamps that allow fast connection of exhibition lights without bolts.",
    faqQuestion: "Are quick-lock truss clamps patentable?",
    faqAnswer: "Yes. Spring-loaded toggle clamps that snap onto standard 2-inch aluminum truss rails are actively patented."
  },
  {
    slug: "airport-terminal",
    name: "Airport Terminal",
    category: "Specialized",
    description: "Passenger terminals featuring automated baggage sorting belts, terminal jet bridges, and high-security gates.",
    complexity: 5,
    basePatentVolume: 19800,
    filingChallenge: "Filing baggage sorting tray switches that route bags at 5 meters per second without jams.",
    faqQuestion: "Are baggage tray diverter rails patentable?",
    faqAnswer: "Yes. Magnetic diverter gates that swing open in under 100 milliseconds are highly patentable."
  },
  {
    slug: "train-station",
    name: "Train Station",
    category: "Specialized",
    description: "Railway hubs featuring platform edge doors and high-capacity electrical catenary connections.",
    complexity: 4,
    basePatentVolume: 8200,
    filingChallenge: "Filing platform barrier doors that synchronize opening with train doors automatically.",
    faqQuestion: "Are platform edge door sync loops patentable?",
    faqAnswer: "Yes. Control loops that communicate via RFID to match door positions are patentable."
  },
  {
    slug: "bus-transit-hub",
    name: "Bus Transit Hub",
    category: "Specialized",
    description: "Urban bus terminals featuring overhead battery charging portals and exhaust ventilation hoods.",
    complexity: 3,
    basePatentVolume: 4100,
    filingChallenge: "Designing pantograph bus chargers that drop automatically onto bus roof contacts.",
    faqQuestion: "Are pantograph bus charging connections patentable?",
    faqAnswer: "Yes. The mechanical connection linkage and the automatic alignment sensor system are patentable."
  },
  {
    slug: "subway-station",
    name: "Subway Station",
    category: "Specialized",
    description: "Underground transit stations requiring deep tunnel ventilation fans and seismic tunnel joints.",
    complexity: 4,
    basePatentVolume: 9600,
    filingChallenge: "Patenting high-displacement seismic joint seals that prevent groundwater ingress.",
    faqQuestion: "Are underground subway joints patentable?",
    faqAnswer: "Yes. Multi-layered rubber expansion joints with integrated waterstops are key transit patents."
  },
  {
    slug: "cruise-ship-terminal",
    name: "Cruise Ship Terminal",
    category: "Specialized",
    description: "Passenger port buildings featuring telescopic gangways and high-capacity customs check stations.",
    complexity: 4,
    basePatentVolume: 5300,
    filingChallenge: "Designing telescopic gangway bridges that adapt to tide movements up to 10 meters.",
    faqQuestion: "Can mobile cruise gangways be patented?",
    faqAnswer: "Yes. Hydraulic auto-leveling support columns that follow ship sway are actively patented."
  },
  {
    slug: "parking-garage",
    name: "Parking Garage",
    category: "Specialized",
    description: "Multi-level concrete parking structures featuring automated space indicator loops and carbon monoxide sensors.",
    complexity: 2,
    basePatentVolume: 2100,
    filingChallenge: "Finding patent novelty in concrete post-tensioning methods or simple ramp layouts.",
    faqQuestion: "Can parking space indicator systems be patented?",
    faqAnswer: "Yes, specifically ultrasonic sensor brackets and LED indicator bars that mount to ceiling conduits."
  },
  {
    slug: "multi-level-park-and-ride",
    name: "Multi-level Park-and-Ride",
    category: "Specialized",
    description: "Transit parking garages featuring integrated solar canopy arrays and automated payment wickets.",
    complexity: 3,
    basePatentVolume: 2800,
    filingChallenge: "Designing solar canopies that mount directly to concrete parking columns without drilling.",
    faqQuestion: "Are parking solar mount brackets patentable?",
    faqAnswer: "Yes. Friction-clamp mounts that grip concrete parapet walls are patentable."
  },
  {
    slug: "police-station",
    name: "Police Station",
    category: "Specialized",
    description: "Secure municipal stations featuring emergency dispatch centers and secure holding rooms.",
    complexity: 3,
    basePatentVolume: 3500,
    filingChallenge: "Designing emergency radio antenna towers that resist wind gusts up to 150 MPH.",
    faqQuestion: "Are dispatch antenna mounts patentable?",
    faqAnswer: "Yes. Vibration damping brackets that protect coaxial cables on high towers are patentable."
  },
  {
    slug: "fire-station",
    name: "Fire Station",
    category: "Specialized",
    description: "First-responder stations featuring quick-opening apparatus bay doors and diesel exhaust extractors.",
    complexity: 3,
    basePatentVolume: 3100,
    filingChallenge: "Filing quick-open door hinges that open apparatus bay doors in under 4 seconds.",
    faqQuestion: "Can fire engine exhaust extractors be patented?",
    faqAnswer: "Yes. Magnetic couplers that attach exhaust hoses to truck pipes and detach automatically are patentable."
  },
  {
    slug: "courthouse",
    name: "Courthouse",
    category: "Specialized",
    description: "Municipal court buildings requiring secure judge transit corridors and blast-resistant lobby glass.",
    complexity: 4,
    basePatentVolume: 4200,
    filingChallenge: "Designing blast-resistant glass frames that absorb impact energy without cracking wall concrete.",
    faqQuestion: "Are blast-resistant window frames patentable?",
    faqAnswer: "Yes. Hollow aluminum frames filled with steel cables that catch the window panel during an explosion are patentable."
  },
  {
    slug: "city-hall",
    name: "City Hall",
    category: "Specialized",
    description: "Civic admin buildings featuring public council chambers and historical archival basements.",
    complexity: 3,
    basePatentVolume: 2600,
    filingChallenge: "Designing archival vault doors that seal air-tight without using electric motors.",
    faqQuestion: "Can mechanical vault door seals be patented?",
    faqAnswer: "Yes. Cam-locking doors that compress neoprene gaskets using hand wheels are patentable."
  },
  {
    slug: "post-office",
    name: "Post Office",
    category: "Specialized",
    description: "Mail sorting and retail facilities featuring automated mail bins and parcel drops.",
    complexity: 2,
    basePatentVolume: 1800,
    filingChallenge: "Patenting parcel drops that prevent anti-fishing (users reaching inside to steal letters).",
    faqQuestion: "Are parcel drop chute doors patentable?",
    faqAnswer: "Yes. Double-flap hinges that close the internal chute before the external door opens are patentable."
  },
  {
    slug: "military-barracks",
    name: "Military Barracks",
    category: "Specialized",
    description: "High-density soldier housing built using blast-resistant concrete panels.",
    complexity: 3,
    basePatentVolume: 2900,
    filingChallenge: "Designing modular wall connectors that prevent progressive collapse during blast impacts.",
    faqQuestion: "Are blast-resistant wall connectors patentable?",
    faqAnswer: "Yes. Steel connectors that allow joint rotation without structural tearing are patentable."
  },
  {
    slug: "prison-facility",
    name: "Prison Facility",
    category: "Specialized",
    description: "Secure correction facilities featuring automated locking bar systems and escape-proof vent grilles.",
    complexity: 4,
    basePatentVolume: 4900,
    filingChallenge: "Designing ventilation grilles that resist mechanical cutting and cannot be disassembled.",
    faqQuestion: "Can security cell locking bars be patented?",
    faqAnswer: "Yes. Multi-point mechanical locking mechanisms operated by central hydraulic cylinders are patentable."
  },
  {
    slug: "bank-branch",
    name: "Bank Branch",
    category: "Specialized",
    description: "Retail banking offices featuring high-security vault compartments and pneumatic cash tubes.",
    complexity: 3,
    basePatentVolume: 3200,
    filingChallenge: "Patenting pneumatic tube switches that route cash carriers without damaging paper bills.",
    faqQuestion: "Are pneumatic cash systems still patented?",
    faqAnswer: "Yes. Optical sensor blocks and mechanical tube diverters that direct carriers are active patent areas."
  },
  {
    slug: "credit-union-office",
    name: "Credit Union Office",
    category: "Specialized",
    description: "Financial office structures featuring walk-up ATM walls and drive-through lanes.",
    complexity: 3,
    basePatentVolume: 2800,
    filingChallenge: "Designing vault ventilation ports that close automatically under thermal drill attacks.",
    faqQuestion: "Can vault drill prevention ports be patented?",
    faqAnswer: "Yes. Ventilation ducts lined with glass rods that shatter to trigger alarms under drilling are patentable."
  },
  {
    slug: "stock-exchange-building",
    name: "Stock Exchange Building",
    category: "Specialized",
    description: "High-frequency trading centers requiring zero-latency server runs and massive video board grids.",
    complexity: 4,
    basePatentVolume: 5100,
    filingChallenge: "Designing cable tray separators that eliminate electromagnetic crosstalk between trading lines.",
    faqQuestion: "Are trading floor cable trays patentable?",
    faqAnswer: "Yes. Metallic shield separators that slide into standard cable conduits are patentable."
  },
  {
    slug: "data-recovery-backup-site",
    name: "Data Recovery Backup Site",
    category: "Specialized",
    description: "Disaster recovery data centers with redundant gas generators and deep water wells.",
    complexity: 4,
    basePatentVolume: 4300,
    filingChallenge: "Patenting automated generator cooling systems that run without external water utilities.",
    faqQuestion: "Are dry-cooler generator systems patentable?",
    faqAnswer: "Yes. Closed-loop radiator fans with automated spray nozzles are patentable."
  },
  {
    slug: "grain-silo",
    name: "Grain Silo",
    category: "Infrastructure",
    description: "Agricultural storage towers requiring dust explosion venting and continuous grain level radars.",
    complexity: 3,
    basePatentVolume: 3800,
    filingChallenge: "Designing explosion vents that release silo pressure before structural walls buckle.",
    faqQuestion: "Are grain silo explosion vents patentable?",
    faqAnswer: "Yes. Magnetic latch relief panels that pop open at specific pressure thresholds are actively patented."
  },
  {
    slug: "greenhouse-facility",
    name: "Greenhouse Facility",
    category: "Infrastructure",
    description: "Commercial plant growth facilities featuring automated curtain shading and hydroponic loops.",
    complexity: 3,
    basePatentVolume: 4900,
    filingChallenge: "Designing double-walled polycarbonate panels that channel condensation to drainage channels.",
    faqQuestion: "Can greenhouse panel joints be patented?",
    faqAnswer: "Yes. Extruded aluminum brackets that grip glazing panels and contain internal condensation gutters are patentable."
  },
  {
    slug: "livestock-barn",
    name: "Livestock Barn",
    category: "Infrastructure",
    description: "Animal housing facilities with automated manure scrapers and natural ridge ventilation openings.",
    complexity: 2,
    basePatentVolume: 1200,
    filingChallenge: "Finding patent novelty in standard metal barn frames or simple gate layouts.",
    faqQuestion: "Can automated barn scrapers be patented?",
    faqAnswer: "Yes. Cable-drive scrapers with pivoting blades that conform to concrete floor slope are patentable."
  },
  {
    slug: "dairy-parlor",
    name: "Dairy Parlor",
    category: "Infrastructure",
    description: "Milking facilities requiring sanitizable pipelines and automated cow gating systems.",
    complexity: 4,
    basePatentVolume: 4500,
    filingChallenge: "Ensuring vacuum milk lines maintain stable vacuum pressure during cows attaching.",
    faqQuestion: "What dairy parlor IP is most valuable?",
    faqAnswer: "Milking claw sensors, automated teat sanitizing sprayers, and rotary parlor platform drives."
  },
  {
    slug: "hydroponic-farm-building",
    name: "Hydroponic Farm Building",
    category: "Infrastructure",
    description: "Vertical indoor farming facilities featuring multi-tier LED racks and nutrient delivery manifolds.",
    complexity: 4,
    basePatentVolume: 6700,
    filingChallenge: "Designing nutrient dosing manifolds that deliver equal chemical ratios to 100+ vertical shelves.",
    faqQuestion: "Are vertical farming racks patentable?",
    faqAnswer: "Yes. Growing rack assemblies with integrated lighting bars and water drainage channels are patentable."
  },
  {
    slug: "solar-power-plant-control-center",
    name: "Solar Power Plant Control Center",
    category: "Infrastructure",
    description: "Power control stations coordinating high-voltage solar panel array tracking.",
    complexity: 4,
    basePatentVolume: 5800,
    filingChallenge: "Patenting solar tracking algorithms that adjust panel tilt during cloudy periods.",
    faqQuestion: "Are solar tracking software scripts patentable?",
    faqAnswer: "Yes, software methods that optimize solar capture by calculating diffuse light reflectances are patentable."
  },
  {
    slug: "wind-farm-substation",
    name: "Wind Farm Substation",
    category: "Infrastructure",
    description: "Substation buildings housing high-voltage transformers and grid interconnection switchgear.",
    complexity: 4,
    basePatentVolume: 7200,
    filingChallenge: "Designing transformer vaults that contain 10,000 gallons of oil leaks during a fire.",
    faqQuestion: "Are transformer oil containment vaults patentable?",
    faqAnswer: "Yes. Vault concrete bases lined with fire-dampening stone beds and oil filtration valves are patentable."
  },
  {
    slug: "hydroelectric-power-station",
    name: "Hydroelectric Power Station",
    category: "Infrastructure",
    description: "Dam turbine halls requiring penstock valve seals and seismic generator mount blocks.",
    complexity: 5,
    basePatentVolume: 11500,
    filingChallenge: "Securing patents for penstock gate seals that withstand water heads of 200+ meters.",
    faqQuestion: "Can water turbine seals be patented?",
    faqAnswer: "Yes. Segmented shaft seals using carbon rings and water cooling loops are actively patented."
  },
  {
    slug: "nuclear-power-facility",
    name: "Nuclear Power Facility",
    category: "Infrastructure",
    description: "Power facilities featuring double-walled containment structures and radioactive pool cooling systems.",
    complexity: 5,
    basePatentVolume: 23000,
    filingChallenge: "Ensuring radioactive water filtration pumps operate continuously without human maintenance.",
    faqQuestion: "What is the patent scope for nuclear containment?",
    faqAnswer: "Nuclear patents cover post-tensioned containment walls, automated fuel rod hooks, and passive cooling pools."
  },
  {
    slug: "waste-water-treatment-plant",
    name: "Waste Water Treatment Plant",
    category: "Infrastructure",
    description: "Treatment stations with high-capacity aerator tanks, sewage clarifiers, and methane gas recovery units.",
    complexity: 4,
    basePatentVolume: 8400,
    filingChallenge: "Patenting aerator nozzles that prevent bacterial biofilm build-up.",
    faqQuestion: "Are waste clarifier scraper drives patentable?",
    faqAnswer: "Yes. Torque-limiting center drives for circular clarifier scrapers are patentable."
  },
  {
    slug: "water-desalination-facility",
    name: "Water Desalination Facility",
    category: "Infrastructure",
    description: "Desalination facilities featuring reverse-osmosis membrane racks and energy recovery turbines.",
    complexity: 5,
    basePatentVolume: 12800,
    filingChallenge: "Designing energy recovery turbines that capture high-pressure brine energy to run input pumps.",
    faqQuestion: "What is the key patent area in water desalination?",
    faqAnswer: "Isobaric energy recovery chambers and reverse osmosis membrane polymer coatings."
  },
  {
    slug: "recycling-sorting-center",
    name: "Recycling Sorting Center",
    category: "Infrastructure",
    description: "Sorting plants with automated paper air-classifiers, magnetic separators, and plastic optical sorters.",
    complexity: 4,
    basePatentVolume: 6200,
    filingChallenge: "Securing patents for optical sorters that classify PET vs HDPE plastics using NIR spectrometry.",
    faqQuestion: "Are recycling optical sorter loops patentable?",
    faqAnswer: "Yes. Spectrometric sorting nozzles and automated air jets that blow bottles off conveyor belts are patentable."
  },
  {
    slug: "self-storage-facility",
    name: "Self-Storage Facility",
    category: "Infrastructure",
    description: "Multi-floor storage buildings featuring individual door alarm switches and climate-control zoning.",
    complexity: 2,
    basePatentVolume: 1400,
    filingChallenge: "Designing wireless latch locks that report battery status to central hubs.",
    faqQuestion: "Are self-storage unit latches patentable?",
    faqAnswer: "Yes. Smart latches that fit standard roll-up doors and utilize low-power mesh networks are patentable."
  },
  {
    slug: "botanical-conservatory",
    name: "Botanical Conservatory",
    category: "Infrastructure",
    description: "Civic green houses featuring curved glass structures and automated misting lines.",
    complexity: 3,
    basePatentVolume: 3200,
    filingChallenge: "Supporting curved glass frame structures that allow maximum light transmittance while meeting snow loads.",
    faqQuestion: "Are botanical conservatory structure rails patentable?",
    faqAnswer: "Yes. Structural aluminum mullions with integrated drainage channels are patentable."
  },
  {
    slug: "observatory-dome",
    name: "Observatory Dome",
    category: "Infrastructure",
    description: "Scientific telescope structures featuring rotating dome rails and absolute thermal shielding.",
    complexity: 4,
    basePatentVolume: 5100,
    filingChallenge: "Designing rotating dome seals that prevent wind infiltration while moving.",
    faqQuestion: "Are observatory dome rotation tracks patentable?",
    faqAnswer: "Yes. Hydrostatic rail supports that float the telescope dome on a thin oil film are patentable."
  },
  {
    slug: "spaceport-launching-facility",
    name: "Spaceport Launching Facility",
    category: "Infrastructure",
    description: "Rocket launch pads featuring cryo-fuel piping, sound suppression water dumps, and lightning towers.",
    complexity: 5,
    basePatentVolume: 28000,
    filingChallenge: "Ensuring pad cooling systems dump 500,000 gallons of water in under 20 seconds during launch.",
    faqQuestion: "What patents apply to space launch structures?",
    faqAnswer: "Cryogenic quick-disconnect valves, pad acoustic water sound absorbers, and blast deflection structures."
  },
  {
    slug: "marine-biology-research-station",
    name: "Marine Biology Research Station",
    category: "Infrastructure",
    description: "Coastal research labs featuring sea-water intakes and corrosion-resistant concrete pools.",
    complexity: 4,
    basePatentVolume: 4900,
    filingChallenge: "Filing concrete formulations that resist sea-water sulfate attacks for 100+ years.",
    faqQuestion: "Are marine concrete mixtures patentable?",
    faqAnswer: "Yes. Concrete containing volcanic ash or specialized pozzolans that resist salt decay is patentable."
  },
  {
    slug: "geothermal-heating-facility",
    name: "Geothermal Heating Facility",
    category: "Infrastructure",
    description: "District heating centers utilizing deep geothermal loop wells and high-temp heat exchangers.",
    complexity: 4,
    basePatentVolume: 6100,
    filingChallenge: "Designing sub-floor heat exchangers that resist mineral scale buildup from geothermal brine.",
    faqQuestion: "Are geothermal scale inhibitors patentable?",
    faqAnswer: "Yes. Electromagnetic scale prevention rings that attach to piping are actively patented."
  },
  {
    slug: "smart-urban-logistics-depot",
    name: "Smart Urban Logistics Depot",
    category: "Infrastructure",
    description: "Intra-city distribution warehouses featuring drone landing pads and automated locker walls.",
    complexity: 4,
    basePatentVolume: 7800,
    filingChallenge: "Designing roof landing pads that recharge drone batteries automatically using induction coils.",
    faqQuestion: "Can drone landing pads be patented?",
    faqAnswer: "Yes. Landing grates with integrated induction coils and barcode visual markers are actively patented."
  },
  {
    slug: "advanced-robotics-testing-site",
    name: "Advanced Robotics Testing Site",
    category: "Infrastructure",
    description: "Testing enclosures requiring dynamic safety nets and absolute optical tracking arrays.",
    complexity: 4,
    basePatentVolume: 8200,
    filingChallenge: "Designing shock-absorbing safety nets that catch runaway heavy robots without tearing.",
    faqQuestion: "Are safety net clamp systems patentable?",
    faqAnswer: "Yes. Clamps that slip under specific friction loads to absorb mechanical kinetic energy are patentable."
  }
];
